version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: EventSpring
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
