spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/event
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: